// export const LOAD_MESSAGES = "LOAD_MESSAGES"
export const LOAD_MESSAGES_FAILED = "LOAD_MESSAGES_FAILED"
export const LOADING_MESSAGES = "LOADING_MESSAGES"
export const ADD_MESSAGE = "ADD_MESSAGE"

export const LOGIN_USER ="LOGIN_USER"